### Environment Variables Declaration
@base_url = http://127.0.0.1:8000

### Create a new record (file upload required)
POST {{base_url}}/test_records/
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test_100.csv"
Content-Type: text/csv

< test_100.csv
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="concurrency"

8
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="task_name"

task_name
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dify_api_url"

http://localhost/v1
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dify_test_agent_id"

7926b8d9-4101-4df7-a1df-6dccf53748ec
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dify_bearer_token"

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZmRkZjdiYmQtNWM3NC00Nzc0LTgxMDUtYTE1ZTMxY2I4MTVjIiwiZXhwIjoxNzYxMDM3MTA0LCJpc3MiOiJTRUxGX0hPU1RFRCIsInN1YiI6IkNvbnNvbGUgQVBJIFBhc3Nwb3J0In0.j2lB8qqrRWfZ2sbcl_FE8Z8qqwo8v1pdLNoYxSGSf3Y
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dify_username"

robertwang123456456456456456
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chatflow_query"

What is the capital of France?
--WebKitFormBoundary7MA4YWxkTrZu0gW--

> {%
    // 提取响应中的Machine的ID并存储在全局变量中
    client.global.set("uuid", response.body.uuid);
%}

### 根据供应商名字和模型名字获取模型
POST {{base_url}}/provider_models/query
accept: application/json
Content-Type: application/json

{
  "model_name": "DeepSeek-V3",
  "provider_name": "volcengine"
}

### 运行测试
POST {{base_url}}/test_records/run_test/{{uuid}}

### 根据uuid获取测试结果
GET {{base_url}}/test_records/{{uuid}}