### Environment Variables Declaration
@base_url = http://127.0.0.1:8000

### List all test records
GET {{base_url}}/test_chatflow_records/
Accept: application/json

###

### Get a record by ID = 1
GET {{base_url}}/test_chatflow_records/1
Accept: application/json

###

### Create a new record (file upload required)
POST {{base_url}}/test_chatflow_records/
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.csv"
Content-Type: text/csv

< test.csv
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

init
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="duration"

10
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="result"

pending
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="concurrency"

64
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dify_api_url"

http://localhost/v1
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dify_test_agent_id"

b35f8cb8-0f9a-4e03-87bf-9f090a3fb589
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dify_bearer_token"

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZmRkZjdiYmQtNWM3NC00Nzc0LTgxMDUtYTE1ZTMxY2I4MTVjIiwiZXhwIjoxNzYwNjc0Njg2LCJpc3MiOiJTRUxGX0hPU1RFRCIsInN1YiI6IkNvbnNvbGUgQVBJIFBhc3Nwb3J0In0.zXPlqaye9DxgR-AdoPoY35A_1Z_5inZiCVk7Fg8wY34
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dify_username"

robertwang123
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="chatflow_query"

What is the capital of France?
--WebKitFormBoundary7MA4YWxkTrZu0gW--


###

### Update record with ID = 1
PATCH {{base_url}}/test_chatflow_records/d333ff0e-aa01-4f37-9262-f59fdb8e860a
Content-Type: application/json

{
  "status": "running",
  "duration": 20,
  "result": "in progress"
}

###

### Delete record with ID = 1
DELETE {{base_url}}/test_chatflow_records/d333ff0e-aa01-4f37-9262-f59fdb8e860a
Accept: application/json

### 运行测试
POST {{base_url}}/test_chatflow_records/run_test/e620792b-dcb7-4bcb-b569-3366cb0c1da8

### 获取所有模型
GET {{base_url}}/provider_models/